on:
  pull_request:
  push:
  schedule:
    - cron: '15 18 * * 0'

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test Action
        uses: ./
        with:
          files: '**/*.md'
          args: '--lang=en_GB --mode=markdown'
  build-push:
    uses: ktht/.github/.github/workflows/docker-build-push.yml@main
